import { pgTable, text, varchar, timestamp, integer, uuid } from "drizzle-orm/pg-core";
import { vector } from "drizzle-orm/pg-core";

// Table to track books/documents
export const books = pgTable("books", {
  id: uuid("id").defaultRandom().primaryKey(),
  title: varchar("title", { length: 255 }).notNull(),
  author: varchar("author", { length: 255 }),
  filePath: text("file_path"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Table to store hierarchical sections/chapters generated by Claude Haiku
export const structuralMetadata = pgTable("structural_metadata", {
  id: uuid("id").defaultRandom().primaryKey(),
  bookId: uuid("book_id").references(() => books.id, { onDelete: "cascade" }).notNull(),
  // parentSectionId can be null if it's top level (e.g., Part -> Chapter)
  parentSectionId: uuid("parent_section_id"), 
  title: varchar("title", { length: 255 }).notNull(),
  level: varchar("level", { length: 50 }).notNull(), // e.g., "part", "chapter", "section"
  orderIndex: integer("order_index").notNull(),
  summary: text("summary"), // Summarized concepts by Claude Haiku 4.5
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Table to store text chunks and their embeddings
export const textChunks = pgTable("text_chunks", {
  id: uuid("id").defaultRandom().primaryKey(),
  sectionId: uuid("section_id").references(() => structuralMetadata.id, { onDelete: "cascade" }).notNull(),
  content: text("content").notNull(),
  // Vector for BAAI/bge-large-en-v1.5 (Together AI)
  embedding: vector("embedding", { dimensions: 1024 }), 
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
